### ISSUE TITLE
[의견제시] todo 타입 변환 제시

### ISSUE THREAD

**Issue by JangHyunjeong** [yoohyunju/react-todo#1]
https://github.com/yoohyunju/react-todo/blob/b2f4e2a66f942c239200bc0a85fc676d24cb26c1/src/TodoList.jsx#L5

todos를  [string] 형태로 담고있는데, [obj] 형태로 고유한 id와 함께 담아두면 수정, 삭제 등의 작업을 할때 오류 없이 작동될수 있을거같습니다!

**Comment by yoohyunju** [comment]
반영하였습니다~
